name: "Tests"

permissions:
  actions: write

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master


jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
           
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Setup python  
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        
    - name: Install requirements
      run: pip install -r requirements.txt
          
    - name: Run tests 
      run: python3 -m pytest test/
      